version: '3.8'
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/code
    ports:
      - "8081:8081"

  frontend:
    build: ./frontend
    ports:
      - "3001:80"
    depends_on:
      - backend